/**
 * ClimaFuse Mock Weather & Station Telemetry API
 * Provides 10 fixed reference stations across the Indian subcontinent.
 */

export const CITIES = [
  {
    id: 'delhi',
    name: 'New Delhi',
    state: 'National Capital Territory (NCR)',
    coords: '28.6139° N, 77.2090° E',
    lat: 28.6139,
    lon: 77.2090,
    awsId: 'AWS: 42182',
    temp: 29.4,
    condition: 'Hazy Sunshine',
    icon: 'wb_sunny',
    alertTier: 'Orange',
    alertDesc: 'Severe Inversion & Particulate Trapping',
    alertDuration: 'ACTIVE (Next 18h)',
    alertColor: '#f97316',
    high: '33.0°',
    low: '19.2°',
    delta: 'Δ -1.1° vs EPS',
    visibility: '2,400m',
    wind: '11.2 km/h',
    windDir: 'NW',
    humidity: '68%',
    dewPoint: '22°',
    pop: '8%',
    rainRate: '0.0 mm/h',
    aqi: 312,
    aqiStatus: 'VERY POOR',
    aqiColor: '#ef4444',
    hourly: [
      { time: '06Z', temp: '29°', icon: 'wb_sunny', highlight: true },
      { time: '10Z', temp: '33°', icon: 'sunny', color: '#f97316' },
      { time: '14Z', temp: '28°', icon: 'partly_cloudy_day' },
      { time: '18Z', temp: '24°', icon: 'bedtime' },
      { time: '22Z', temp: '21°', icon: 'foggy' },
      { time: '02Z', temp: '20°', icon: 'foggy' },
    ],
    blend: { ec: 42, ai: 35, ncmrwf: 23, reliability: '94.8%' },
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra Coastal Plain',
    coords: '19.0760° N, 72.8777° E',
    lat: 19.0760,
    lon: 72.8777,
    awsId: 'AWS: 43003',
    temp: 31.8,
    condition: 'Thunderstorm with Gusts',
    icon: 'thunderstorm',
    alertTier: 'Red',
    alertDesc: 'Severe Convective Cell & Coastal Surge',
    alertDuration: 'ACTIVE (Next 6h)',
    alertColor: '#ef4444',
    high: '33.5°',
    low: '25.0°',
    delta: 'Δ +1.8° vs EPS',
    visibility: '1,800m',
    wind: '28.4 km/h',
    windDir: 'SW',
    humidity: '88%',
    dewPoint: '26°',
    pop: '85%',
    rainRate: '14.2 mm/h',
    aqi: 94,
    aqiStatus: 'MODERATE',
    aqiColor: '#fbbf24',
    hourly: [
      { time: '06Z', temp: '31°', icon: 'thunderstorm', highlight: true },
      { time: '10Z', temp: '32°', icon: 'rainy' },
      { time: '14Z', temp: '30°', icon: 'thunderstorm', color: '#ef4444' },
      { time: '18Z', temp: '28°', icon: 'cloud' },
      { time: '22Z', temp: '27°', icon: 'cloud' },
      { time: '02Z', temp: '26°', icon: 'partly_cloudy_day' },
    ],
    blend: { ec: 58, ai: 24, ncmrwf: 18, reliability: '96.2%' },
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka Deccan Plateau',
    coords: '12.9716° N, 77.5946° E',
    lat: 12.9716,
    lon: 77.5946,
    awsId: 'AWS: 43295',
    temp: 23.1,
    condition: 'Partly Cloudy Breeze',
    icon: 'partly_cloudy_day',
    alertTier: 'Green',
    alertDesc: 'Normal Synoptic Regime / Clear Sky',
    alertDuration: 'NOMINAL',
    alertColor: '#10b981',
    high: '26.8°',
    low: '17.4°',
    delta: 'Δ -0.4° vs EPS',
    visibility: '6,000m',
    wind: '14.5 km/h',
    windDir: 'E',
    humidity: '56%',
    dewPoint: '16°',
    pop: '12%',
    rainRate: '0.0 mm/h',
    aqi: 62,
    aqiStatus: 'GOOD',
    aqiColor: '#10b981',
    hourly: [
      { time: '06Z', temp: '23°', icon: 'partly_cloudy_day', highlight: true },
      { time: '10Z', temp: '26°', icon: 'wb_sunny' },
      { time: '14Z', temp: '25°', icon: 'partly_cloudy_day' },
      { time: '18Z', temp: '21°', icon: 'bedtime' },
      { time: '22Z', temp: '19°', icon: 'bedtime' },
      { time: '02Z', temp: '18°', icon: 'bedtime' },
    ],
    blend: { ec: 38, ai: 45, ncmrwf: 17, reliability: '97.5%' },
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal Gangetic Delta',
    coords: '22.5726° N, 88.3639° E',
    lat: 22.5726,
    lon: 88.3639,
    awsId: 'AWS: 42807',
    temp: 28.0,
    condition: 'Overcast & Humid',
    icon: 'cloud',
    alertTier: 'Yellow',
    alertDesc: 'Deltaic Boundary Layer Moisture Advection',
    alertDuration: 'WATCH (Next 24h)',
    alertColor: '#fbbf24',
    high: '31.2°',
    low: '23.8°',
    delta: 'Δ +0.6° vs EPS',
    visibility: '3,200m',
    wind: '9.8 km/h',
    windDir: 'SE',
    humidity: '79%',
    dewPoint: '24°',
    pop: '35%',
    rainRate: '0.5 mm/h',
    aqi: 182,
    aqiStatus: 'UNHEALTHY',
    aqiColor: '#f97316',
    hourly: [
      { time: '06Z', temp: '28°', icon: 'cloud', highlight: true },
      { time: '10Z', temp: '31°', icon: 'cloud' },
      { time: '14Z', temp: '29°', icon: 'rainy', color: '#fbbf24' },
      { time: '18Z', temp: '26°', icon: 'bedtime' },
      { time: '22Z', temp: '25°', icon: 'bedtime' },
      { time: '02Z', temp: '24°', icon: 'cloud' },
    ],
    blend: { ec: 44, ai: 36, ncmrwf: 20, reliability: '93.4%' },
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Coromandel Coast (Tamil Nadu)',
    coords: '13.0827° N, 80.2707° E',
    lat: 13.0827,
    lon: 80.2707,
    awsId: 'AWS: 43279',
    temp: 30.2,
    condition: 'Northeast Monsoon Squalls',
    icon: 'rainy',
    alertTier: 'Yellow',
    alertDesc: 'Coastal Convergence Bands Active',
    alertDuration: 'WATCH (Next 12h)',
    alertColor: '#fbbf24',
    high: '32.0°',
    low: '24.5°',
    delta: 'Δ +0.9° vs EPS',
    visibility: '4,000m',
    wind: '22.1 km/h',
    windDir: 'NE',
    humidity: '82%',
    dewPoint: '25°',
    pop: '65%',
    rainRate: '4.2 mm/h',
    aqi: 88,
    aqiStatus: 'SATISFACTORY',
    aqiColor: '#10b981',
    hourly: [
      { time: '06Z', temp: '30°', icon: 'rainy', highlight: true },
      { time: '10Z', temp: '31°', icon: 'rainy' },
      { time: '14Z', temp: '29°', icon: 'cloud' },
      { time: '18Z', temp: '27°', icon: 'rainy' },
      { time: '22Z', temp: '26°', icon: 'cloud' },
      { time: '02Z', temp: '25°', icon: 'rainy' },
    ],
    blend: { ec: 52, ai: 30, ncmrwf: 18, reliability: '94.1%' },
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat Semi-Arid Basin',
    coords: '23.0225° N, 72.5714° E',
    lat: 23.0225,
    lon: 72.5714,
    awsId: 'AWS: 42647',
    temp: 34.5,
    condition: 'Dry High Solar Radiation',
    icon: 'sunny',
    alertTier: 'Orange',
    alertDesc: 'Elevated Daytime Surface Heat Flux',
    alertDuration: 'ACTIVE (Next 12h)',
    alertColor: '#f97316',
    high: '36.8°',
    low: '21.0°',
    delta: 'Δ -0.7° vs EPS',
    visibility: '5,000m',
    wind: '13.0 km/h',
    windDir: 'NW',
    humidity: '38%',
    dewPoint: '14°',
    pop: '2%',
    rainRate: '0.0 mm/h',
    aqi: 220,
    aqiStatus: 'POOR',
    aqiColor: '#f97316',
    hourly: [
      { time: '06Z', temp: '34°', icon: 'sunny', highlight: true },
      { time: '10Z', temp: '36°', icon: 'sunny', color: '#f97316' },
      { time: '14Z', temp: '33°', icon: 'wb_sunny' },
      { time: '18Z', temp: '28°', icon: 'bedtime' },
      { time: '22Z', temp: '24°', icon: 'bedtime' },
      { time: '02Z', temp: '22°', icon: 'bedtime' },
    ],
    blend: { ec: 36, ai: 50, ncmrwf: 14, reliability: '98.0%' },
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana Central Plateau',
    coords: '17.3850° N, 78.4867° E',
    lat: 17.3850,
    lon: 78.4867,
    awsId: 'AWS: 43128',
    temp: 27.6,
    condition: 'Clear Atmosphere',
    icon: 'clear_day',
    alertTier: 'Green',
    alertDesc: 'Stable Continental Equilibrium',
    alertDuration: 'NOMINAL',
    alertColor: '#10b981',
    high: '30.4°',
    low: '19.5°',
    delta: 'Δ -0.2° vs EPS',
    visibility: '7,000m',
    wind: '10.5 km/h',
    windDir: 'SE',
    humidity: '52%',
    dewPoint: '17°',
    pop: '5%',
    rainRate: '0.0 mm/h',
    aqi: 110,
    aqiStatus: 'MODERATE',
    aqiColor: '#fbbf24',
    hourly: [
      { time: '06Z', temp: '27°', icon: 'clear_day', highlight: true },
      { time: '10Z', temp: '30°', icon: 'wb_sunny' },
      { time: '14Z', temp: '28°', icon: 'partly_cloudy_day' },
      { time: '18Z', temp: '24°', icon: 'bedtime' },
      { time: '22Z', temp: '21°', icon: 'bedtime' },
      { time: '02Z', temp: '20°', icon: 'bedtime' },
    ],
    blend: { ec: 40, ai: 42, ncmrwf: 18, reliability: '96.5%' },
  },
  {
    id: 'pune',
    name: 'Pune',
    state: 'Western Maharashtra Foothills',
    coords: '18.5204° N, 73.8567° E',
    lat: 18.5204,
    lon: 73.8567,
    awsId: 'AWS: 43063',
    temp: 26.2,
    condition: 'Partly Cloudy',
    icon: 'partly_cloudy_day',
    alertTier: 'Green',
    alertDesc: 'Orographic Leeward Stability',
    alertDuration: 'NOMINAL',
    alertColor: '#10b981',
    high: '29.5°',
    low: '17.8°',
    delta: 'Δ +0.1° vs EPS',
    visibility: '5,500m',
    wind: '12.0 km/h',
    windDir: 'W',
    humidity: '61%',
    dewPoint: '18°',
    pop: '15%',
    rainRate: '0.0 mm/h',
    aqi: 98,
    aqiStatus: 'SATISFACTORY',
    aqiColor: '#10b981',
    hourly: [
      { time: '06Z', temp: '26°', icon: 'partly_cloudy_day', highlight: true },
      { time: '10Z', temp: '29°', icon: 'wb_sunny' },
      { time: '14Z', temp: '28°', icon: 'cloud' },
      { time: '18Z', temp: '23°', icon: 'bedtime' },
      { time: '22Z', temp: '20°', icon: 'bedtime' },
      { time: '02Z', temp: '19°', icon: 'bedtime' },
    ],
    blend: { ec: 45, ai: 38, ncmrwf: 17, reliability: '95.6%' },
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan Semi-Arid Zone',
    coords: '26.9124° N, 75.7873° E',
    lat: 26.9124,
    lon: 75.7873,
    awsId: 'AWS: 42348',
    temp: 32.1,
    condition: 'Clear & Warm',
    icon: 'wb_sunny',
    alertTier: 'Yellow',
    alertDesc: 'High Diurnal Temperature Swing',
    alertDuration: 'WATCH (Next 24h)',
    alertColor: '#fbbf24',
    high: '35.0°',
    low: '18.5°',
    delta: 'Δ -0.5° vs EPS',
    visibility: '4,800m',
    wind: '11.5 km/h',
    windDir: 'N',
    humidity: '34%',
    dewPoint: '12°',
    pop: '0%',
    rainRate: '0.0 mm/h',
    aqi: 195,
    aqiStatus: 'UNHEALTHY',
    aqiColor: '#f97316',
    hourly: [
      { time: '06Z', temp: '32°', icon: 'wb_sunny', highlight: true },
      { time: '10Z', temp: '35°', icon: 'sunny', color: '#fbbf24' },
      { time: '14Z', temp: '33°', icon: 'wb_sunny' },
      { time: '18Z', temp: '26°', icon: 'bedtime' },
      { time: '22Z', temp: '22°', icon: 'bedtime' },
      { time: '02Z', temp: '20°', icon: 'bedtime' },
    ],
    blend: { ec: 39, ai: 46, ncmrwf: 15, reliability: '97.1%' },
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    state: 'Central Uttar Pradesh (Gangetic Plain)',
    coords: '26.8467° N, 80.9462° E',
    lat: 26.8467,
    lon: 80.9462,
    awsId: 'AWS: 42369',
    temp: 28.7,
    condition: 'Hazy Morning Mist',
    icon: 'foggy',
    alertTier: 'Orange',
    alertDesc: 'Boundary Layer Particulate Trapping',
    alertDuration: 'ACTIVE (Next 16h)',
    alertColor: '#f97316',
    high: '32.4°',
    low: '19.8°',
    delta: 'Δ -0.8° vs EPS',
    visibility: '2,100m',
    wind: '8.4 km/h',
    windDir: 'E',
    humidity: '72%',
    dewPoint: '23°',
    pop: '10%',
    rainRate: '0.0 mm/h',
    aqi: 285,
    aqiStatus: 'POOR',
    aqiColor: '#f97316',
    hourly: [
      { time: '06Z', temp: '28°', icon: 'foggy', highlight: true },
      { time: '10Z', temp: '32°', icon: 'wb_sunny' },
      { time: '14Z', temp: '30°', icon: 'partly_cloudy_day' },
      { time: '18Z', temp: '25°', icon: 'bedtime' },
      { time: '22Z', temp: '22°', icon: 'foggy' },
      { time: '02Z', temp: '21°', icon: 'foggy' },
    ],
    blend: { ec: 43, ai: 37, ncmrwf: 20, reliability: '94.5%' },
  },
];

/**
 * Returns all 10 meteorological stations.
 */
export function getCities() {
  return CITIES;
}

/**
 * Mock async fetch simulating network/API delay.
 */
export async function fetchCities() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(CITIES);
    }, 100);
  });
}

/**
 * Returns a specific station by ID.
 */
export function getCityById(id) {
  return CITIES.find((c) => c.id === id) || CITIES[0];
}
